### ISSUE TITLE
SDK does not support bitcode

### ISSUE THREAD

**Issue by marco1981** [Napster/napster-ios-sdk#1]
**Description**

napster-ios-sdk does not support bitcode enabled

**Versions**

Napster iOS SDK version 2.0

**Severity**

Major

**Steps to Reproduce**

Create a project that supports bitcode and include the NapsterKit. Try to archive it.

**Actual behaviour**

Impossible to link the project when bitcode is enabled:
```

ld: bitcode bundle could not be generated because
'<project path>/NapsterKit.framework/NapsterKit(NKPayloadOperation.o)' was built 
without full bitcode. 
All object files and libraries for bitcode must be generated from Xcode Archive 
or Install build for architecture armv7

```

**Expected behaviour**

Expect bitcode to be supported

**Comment by marco1981** [comment]
Release 2.1.0:
Issue has not been fixed on this version.

Message returned by XCode 8.3.3:

```
ld: bitcode bundle could not be generated because
'<project path>/NapsterKit.framework/NapsterKit(NKPayloadOperation.o)' was built
without full bitcode.
```

**Comment by mijo-gracanin** [comment]
@marco1981 I just downloaded a zip from this repo, added NapsterKit to a new project and archived it successfully.

Can you please provide example project?

**Comment by marco1981** [comment]
@mijo-gracanin 
Once created a new project on XCode and added NapsterKit, you can just add a simple class on your project in Swift. For example:

```
import NapsterKit

class NapsterTest {
    
    var track: NKTrack?
    
}
```
Please be sure to have in your project's "Build Settings" flag "Enable Bitcode" to Yes (it is yes by default).
Then you can try to Archive it and you'll see an error message similar to this:
```
ld: bitcode bundle could not be generated because '<project path>/NapsterKit.framework/NapsterKit(NKTrack.o)' was built without full bitcode. 
```

**Comment by mijo-gracanin** [comment]
@marco1981 must be something else. Archive worked: [screenshot](https://ibb.co/hRLrxv)

**Comment by marco1981** [comment]
@mijo-gracanin were you able to replicate this issue?

**Comment by mijo-gracanin** [comment]
@marco1981 Yes, I reproduced the issue.

**Comment by mijo-gracanin** [comment]
@marco1981 can you please pull latest changes and see if error still occurs?

**Comment by marco1981** [comment]
Error is not occurring anymore. Thanks. You can close this issue. I hope you'll create a release soon.
