### ISSUE TITLE
Playing audio in background with swift 3

### ISSUE THREAD

**Issue by aweiner42** [Napster/napster-ios-sdk#11]
We have been integrating the NapsterKit into our swift application and we are bouncing into the issue when we play and our app goes totally into the background it crashes. 
When running the app playing it continuously generates the error below but it does not crash the app:
 [NKGenericPlayContext meteringSourceID:]: unrecognized selector. 

I am responding to the audio session changes and playing multiple tracks (really cool).
When the app gets interrupted with a phone call or on the lock screen it plays fine.
When the app goes to the background the unrecognized selector error kills the app.
Any ideas what I may be missing. The demo app works great in the background.
     Thanks

"app delegate backgrounding app"
2017-12-16 16:33:04.019451-0500 PlayAnAlbum[1259:523993] -[NKGenericPlayContext meteringSourceID:]: unrecognized selector sent to instance 0x1c423b740
2017-12-16 16:33:04.019777-0500 PlayAnAlbum[1259:523993] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NKGenericPlayContext meteringSourceID:]: unrecognized selector sent to instance 0x1c423b740'
*** First throw call stack:
(0x1814f3d38 0x180a08528 0x1815011f8 0x10448b620 0x10448c738 0x1044721cc 0x18148612c 0x1814856cc 0x181485430 0x1815029f4 0x1813bc3e0 0x181ddc498 0x18ab6f69c 0x18ac72338 0x18ab6f538 0x18adf93a8 0x18b561760 0x18b56158c 0x18b2dd9c0 0x18b472fc8 0x18b2dd870 0x18b0c7850 0x18af6cbd8 0x183b9621c 0x10489d45c 0x1048a9b74 0x183bc9a04 0x183bc96a8 0x183bc9c44 0x18149c358 0x18149c2d8 0x18149bb60 0x181499738 0x1813ba2d8 0x18324bf84 0x18a966880 0x102f62e34 0x180ede56c)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by mijo-gracanin** [comment]
Hi @aweiner42 
I'll investigate the issue.

**Comment by mijo-gracanin** [comment]
Hey @aweiner42 , I merged in a fix for the issue.

**Comment by aweiner42** [comment]
Awesome... worked like a charm
    Thanks
